### ISSUE TITLE
`pt.imshow` yields two identical outputs in jupyter notebook

### ISSUE THREAD

**Issue by Michael-Liao** [LabForComputationalVision/pyrtools#12]
I'm trying to replicate the steerable pyramid notebook. The results were correct. However, it `pt.imshow` always shows 2 sets of output images (shown below). Is there any way to solve this?

[!dual_output](https://i.imgur.com/fQv3Frb.png)

### system setup
* ubuntu 20.04
* python 3.7.7
* pyrtools 1.0.0 (installed via `pip`)

**Comment by billbrod** [comment]
Yes there is -- `pt.imshow` both displays and returns the matplotlib figure, and jupyter will display a figure if it's returned by the last line of the code (similar to how it displays an array if your last line is something like `np.array([1,2,3])`). There's similar discussion [here](https://stackoverflow.com/questions/36685031/why-is-jupyter-notebook-creating-duplicate-plots-when-making-updating-plots) and [here](https://github.com/statsmodels/statsmodels/issues/1265).

The way to handle it is to either assign the figure to a variable (`fig = pt.imshow(filt_list, vrange='auto', zoom=10)`) or put a semicolon afterwards to suppress the output (`pt.imshow(filt_list, vrange='auto', zoom=10);`), which is what we do in our included notebook.
