### ISSUE TITLE
TUTORIALS/03_steerable_pyramids.ipynb typo

### ISSUE THREAD

**Issue by devernay** [LabForComputationalVision/pyrtools#5]
At this place in the tutorial:
```
# look at all orientation bands at one level (scale):
imgList = []
for b in range(pyr.num_scales):
```
it should be `num_orientations` instead of `num_scale` (by chance, it happens to be the same here, since order=3 and height=4)

This is a very useful package, which allowed me to play with the steerable pyramids I heard about 25 years ago! That's a fantastic and underrated tool.

**Comment by kbonnen** [comment]
We're glad you like the package.  Thanks for reporting the bug!
